/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ComptonScattering;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

/**
 *
 * @author Geonmo
 */
public class ComptonViewPanel extends javax.swing.JPanel {

    int step;
    /**
     * Creates new form ComptonViewPanel
     */
    public ComptonViewPanel() {
        initComponents();
        step = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /**
    public void drawWave(Graphics g,int first_pixel) {
        //step = step+1;
        int amp = 25;
        for( int i=0; i<50; i++ ){
            double value = Math.sin(i*0.5)*amp;
            double next_value = Math.sin((i+1)*0.5)*amp;
            g.drawLine(i+first_pixel,(int)value+this.getHeight()/2, i+1+first_pixel, (int)next_value+this.getHeight()/2);
            System.out.printf("%d %f %d %f\n",i+first_pixel,value, i+1+first_pixel,next_value);
        }
    }
    */
    public void drawElectron(Graphics g, Point pos){
        //int height = this.getHeight();
        //int width = this.getWidth();
        
        g.fillOval(pos.x-10, pos.y-10,20,20);
    }
    public void paintComponent(Graphics g)                
    {   
        super.paintComponent(g);
        step = step+1;        
        int amp = 25;
        if ( step < this.getWidth()/2 ) { 
            for( int i=0; i<step; i++ ){
            
                double value = Math.sin(i*0.25)*amp;
                double next_value = Math.sin((i+1)*0.25)*amp;
                g.drawLine(i,(int)value+this.getHeight()/2, i+1, (int)next_value+this.getHeight()/2);
                //System.out.printf("%d %f %d %f\n",i+first_pixel,value, i+1+first_pixel,next_value);
            }
        }
        else {
            
        }
        
      
        int height = this.getHeight();
        int width = this.getWidth();
        drawElectron(g, new Point(width/2, height/2));
            
        g.setColor(Color.black);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
