/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RutherfordScattering;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
/**
 *
 * @author Geonmo
 */
public class ImpactViewPanel extends javax.swing.JPanel {

    AlphaParticle alpha;
    Nucleus nucle;
    private int impactParameter=0;
    private double initVelocity=0.0;
    
    
    /**
     * Creates new form ViewPanel
     */
    
    public ImpactViewPanel() {
        initComponents();
        resetPanel();
      
    }
    public void resetPanel(){
        if ( initVelocity !=0.0 || impactParameter !=0 ) {
            alpha = new AlphaParticle(impactParameter, initVelocity);
        }
        else {
            alpha = new AlphaParticle();
        }        
        nucle = new Nucleus();   
        System.out.printf("ip : %d, vel : %f",impactParameter, initVelocity);
    }
    public void setIP(int ip) {
        impactParameter = ip;
    }
    public void setVelocity( double rel_velocity ) {
        initVelocity = 3.0e8* rel_velocity;
    }
    public double getDistance() {
        return alpha.pos.distance( nucle.pos);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    
    
    public void goStep(){
        alpha.nextStep(nucle);
    }
    

    @Override
    protected void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs); //To change body of generated methods, choose Tools | Templates.       
        grphcs.drawImage(alpha.img, alpha.pos.x-alpha.size/2,alpha.pos.y-alpha.size/2, this);    
        grphcs.drawImage(nucle.img, nucle.pos.x-nucle.size/2,nucle.pos.y-nucle.size/2, this);    

    }
    
    
}
